### ISSUE TITLE
Armory

### ISSUE THREAD

**Issue by Matt-One** [alexandre433/CraftedWeb#1]
Will you add an armory too? :)

**Comment by Matt-One** [comment]
U can find some character base stats in Character_stats table and the equipped item maybe in character_inventory but then you need to see how to show the item image xD
I'm a 0% coder so i can't help you... anyway good luck :)

**Comment by alexandre433** [comment]
Thanks for the help :P

I'm going to try to get the armory from fusioncms and implement it to craftedweb

**Comment by alexandre433** [comment]
#2
