### ISSUE TITLE
Error upon fresh files installing as of 27/12-2018

### ISSUE THREAD

**Issue by Snowie493** [alexandre433/CraftedWeb#9]
Fatal error: Uncaught Error: Call to undefined function opcache_compile_file() in C:\xampp\htdocs\core\includes\classes\cache.php:37 Stack trace: #0 C:\xampp\htdocs\core\includes\classes\cache.php(89): Cache->__construct() #1 C:\xampp\htdocs\core\includes\loader.php(23): require_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\index.php(21): require('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\core\includes\classes\cache.php on line 37

**Comment by alexandre433** [comment]
Like I said in #2 You WILL have errors after installing because I'm overhauling the coding and it need a bit of time until it's functional. Go to the releases - https://github.com/alexandre433/CraftedWeb/releases - and download the non-beta version.
